# Generated by Django 2.1 on 2018-08-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CF', 'Conferencia'), ('SM', 'Seminario'), ('CG', 'Congreso'), ('CS', 'Curso')], default='CF', max_length=2)),
                ('lugar', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(verbose_name='fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha fin')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('modo', models.CharField(choices=[('PR', 'Presencial'), ('VR', 'Virtual')], default='PR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Usuario'),
        ),
    ]
