# Generated by Django 2.1 on 2018-08-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20180814_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
