# Generated by Django 2.1 on 2018-08-16 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha inicio'),
        ),
    ]
